Try multiple files signing.

diff --git a/.github/workflows/test_and_merge.yml b/.github/workflows/test_and_merge.yml
--- a/.github/workflows/test_and_merge.yml
+++ b/.github/workflows/test_and_merge.yml
@@ -129,38 +129,47 @@ jobs:
           run: |
             test -f $output_folder/esl-erlang-compat-21.2.6-1.noarch.rpm || { echo "Signed file not found"; exit 1; }
 
-#    integration-test-multiple-file-signing:
-#      runs-on: ubuntu-latest
-#      needs: build-and-push-image
-#      env:
-#        output_folder: SignedPackages
-#      steps:
-#        - name: Get source code from repository.
-#          uses: actions/checkout@v2
-#
-#        - name: Install rpm support to check signature.
-#          run: |
-#            sudo apt install rpm librpmsign9
-#
-#        - name: Import public key whose signature wh are going to verify.
-#          run: |
-#            sudo rpm --import src/tests/resources/test_certificate/test_pub.gpg
-#
-#        - name: Try to use rpmsign as an action to sign multiple packages.
-#          uses: dante-signal31/rpmsign@staging
-#          with:
-#            # Actually signing with dummy certificate you can find at src/tests/resources/test_certificate
-#            gpg_private_key: ${{ secrets.PRIVATE_GPG_KEY }}
-#            gpg_private_key_password: ${{ secrets.GPG_KEY_PASSWORD }}
-#            gpg_name: Dummy certificate for automated testing (Don\'t use for sign anything important. Use for testing signing in automated workflows.) <dummy_test@gmail.com>
-#            rpm_folder: src/tests/resources/packages/
-#            output_folder: ${{ env.output_folder }}/
-#
-#        - name: Check that rpmsign actually signed the files.
-#          run: |
-#            rpm --checksig $output_folder/ConsoleKit-0.3.0-2.fc10.i386.rpm || { echo "Signature not correct"; exit 1; }
-#            rpm --checksig $output_folder/ImageMagick-perl-6.4.0.10-2.fc10.i386.rpm || { echo "Signature not correct"; exit 1; }
-#            rpm --checksig $output_folder/MySQL-python-1.2.2-7.fc10.i386.rpm || { echo "Signature not correct"; exit 1; }
+    integration-test-multiple-file-signing:
+      runs-on: ubuntu-latest
+      needs: build-and-push-image
+      env:
+        gpg_private_key: ${{ secrets.PRIVATE_GPG_KEY }}
+        gpg_private_key_file: test_priv.gpg
+        gpg_private_key_password: ${{ secrets.GPG_KEY_PASSWORD }}
+        gpg_name: "Dummy certificate for automated testing (Don\'t use for sign anything important. Use for testing signing in automated workflows.) <dummy_test@gmail.com>"
+        rpm_file: src/tests/resources/packages/package_without_sign/esl-erlang-compat-21.2.6-1.noarch.rpm
+        output_folder: SignedPackages
+      steps:
+        - name: Get source code from repository.
+          uses: actions/checkout@v2
+
+        - name: Import public key whose signature wh are going to verify.
+          run: |
+            sudo rpm --import src/tests/resources/test_certificate/test_pub.gpg
+
+        - name: Create private key file from secret.
+          run: |
+            echo $gpg_private_key | base64 -di > $gpg_private_key_file
+
+        - name: Try to use rpmsign as an action to sign multiple packages.
+          uses: dante-signal31/rpmsign@staging
+          with:
+            # Actually signing with dummy certificate you can find at src/tests/resources/test_certificate
+            gpg_private_key: ${{ env.gpg_private_key_file }}
+            gpg_private_key_password: ${{ secrets.GPG_KEY_PASSWORD }}
+            gpg_name: "Dummy certificate for automated testing (Don\'t use for sign anything important. Use for testing signing in automated workflows.) <dummy_test@gmail.com>"
+            rpm_folder: src/tests/resources/packages/
+            output_folder: ${{ env.output_folder }}/
+
+        - name: Remove private key file.
+          run: |
+            rm $gpg_private_key_file
+
+        - name: Check that signed files are at output folder.
+          run: |
+            test -f $output_folder/ConsoleKit-0.3.0-2.fc10.i386.rpm || { echo "Signed file not found"; exit 1; }
+            test -f $output_folder/ImageMagick-perl-6.4.0.10-2.fc10.i386.rpm || { echo "Signed file not found"; exit 1; }
+            test -f $output_folder/MySQL-python-1.2.2-7.fc10.i386.rpm || { echo "Signed file not found"; exit 1; }
 
 #    merge-master:
 #      runs-on: ubuntu-latest
